### ISSUE TITLE
Adding User Profiles and Twitter Lists

### ISSUE THREAD

**Issue by dothedrippy** [anomalyce/twitter-idle-autorefresh#3]
Hi,

I love your addon! It's very helpful. I was wondering if you could adding user profiles or twitter custom lists.

**Comment by anomalyce** [comment]
Hey.

Thanks! It's funny, I initially had plans for this, including search results, but never really got around to it, and decided to abandon it in the last update because no one had really asked for it. Since then I started using the lists feature myself, and have missed the auto refresh for it.

Currently, the add-on works by faking a user click on the Twitter logo, which obviously only works for the home feed. Let me try and figure out a better/universal way of refreshing the feeds and I'm more than happy to implement this. If not, I might just fall back to using a separate DOM selector for each feed (home, profiles, search results or lists).

I can't promise I'll have this done within the next few days, but more than happy to have a look at it :-)

**Comment by dothedrippy** [comment]
No worries! I appreciate you taking the time to respond and taking a look at it. 

I love using the list feature to check out certain users who I like to focus on because my twitter feed has gotten to large. I'm not sure of a more universal way of refreshing feeds. I end up spamming ctrl + r, lol. 

Thank you!

**Comment by anomalyce** [comment]
Absolutely! Appreciate you using the add-on :-)

Yeah, like I mentioned in my previous comment, only a few days ago I decided to go the exact same route, haha.

Preferably, I'd like to avoid a full page refresh as the user experience would be a lot choppier. I've been experimenting a bit with force-scrolling the feed to have Twitter load in the tweets themselves, but again, the UX is a bit too choppy for my liking. I want it to be at a point where loading new tweets isn't going to attract your focus more than necessary.

I'm about to call it for the evening though, but I'm sure I'll find something suitable eventually :-) I'll notify you through this issue whenever I find something.

**Comment by anomalyce** [comment]
All right, I decided to round up the current, choppy scrolling-based method and push it as an optional temporary/experimental feature.

You can update your add-on to v1.3.0 (https://addons.mozilla.org/en-US/firefox/addon/twitter-idle-autorefresh/) and enable the channels in the add-on preferences.

Again, it's not perfect, it will be choppy, and it may grab your focus a lot more than you'd want it to, but hey, it should beat manual refreshing, haha :-)

**Comment by dothedrippy** [comment]
Awesome! Thank you. I'll test it out right now and let you know how it goes. It will definitely beat manual refreshing hahaha
